### ISSUE TITLE
Audio bit rate should be Kbps not kbps

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#100]
@argilo This should be a real simple fix :)

**Comment by argilo** [comment]
@pclov3r I'm not sure exactly what you're proposing here. Is the calculation not correct?

**Comment by classicfm** [comment]
If you are saying that the current lowercase 'k' implies kilobytes per second, that's wrong. That's usually written as kB/sec. Kbps and kbps mean the same thing, and kbps seems to be the prevailing style.

**Comment by argilo** [comment]
The calculation itself and the abbreviation look correct to me so I'll close this for now.

**Comment by pclov3r** [comment]
My error

I've typically seen Kilobits refereed as Kbps but I guess it can be be both Kbps or kbps and mean the same so it is indeed correct.
