### ISSUE TITLE
expected 7 got 35 bytes??

### ISSUE THREAD

**Issue by cybernard** [theori-io/nrsc5#127]
04:59:08 DEBUG output.c:390: Artist: Blake Shelton
04:59:08 DEBUG output.c:463: XHDR tag: 36 75 4B BE 00 02 7E 65
04:59:08 DEBUG output.c:129: Audio bit rate: 46.7 kbps
04:59:09 INFO  sync.c:332: MER: 5.4 dB (lower), 7.1 dB (upper)
04:59:09 INFO  decode.c:77: BER: 0.017806, avg: 0.021572, min: 0.002011, max: 0.111192
04:59:09 DEBUG output.c:646: SLWMIL$$0235380000.png expected 7, got 35

What does expected 7, got 35 mean?

**Comment by argilo** [comment]
Files arrive in chunks, and each chunk has a sequence number. nrsc5 expects the chunks to arrive in sequential order, but interference or insufficient signal strength can corrupt the data, causing chunks to be missed or the sequence number to be corrupted. In those cases, you'll see this message.
