### ISSUE TITLE
Upper and Lower sideband MER reversed? 

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#130]
So, I was listening to a HD station with serious adjacent channel interference and noticed this.

`15:36:34 INFO  sync.c:332: MER: 9.2 dB (lower), -2.2 dB (upper)`

The FFT of the station currently looks like this.

![sdr console_2017-12-26_15-39-06](https://user-images.githubusercontent.com/10610227/34366618-111fda82-ea53-11e7-9687-9f24ad5ba713.png)

Is this intended? To me it looks like the MER output may be reversed.

**Comment by argilo** [comment]
Yes, it's intended. From http://www.nrscstandards.org/sg/nrsc-5-d-reference-docs/1011s.pdf section 14.2.2:

> The negative exponent in the up-conversion equation indicates that the RF spectrum is inverted in
comparison to the baseband spectrum. This means that the negative-numbered subcarriers / lower
sideband occupy the higher frequencies within the RF channel. Similarly, the positive-numbered
subcarriers / upper sideband occupy the lower frequencies within the RF channel.
