### ISSUE TITLE
Experimental branch terminal output not redirecting to file

### ISSUE THREAD

**Issue by BrodieBruce901** [theori-io/nrsc5#14]
While attempting to redirect the output using "nrsc5 91100000 1 2>&1 >> hdlog.log" no output is written to the file. Redirecting the output using this method prior to running the experimental branch worked. This is on the working x86 machine.

**Comment by awesie** [comment]
The change to the logging now outputs everything to stderr. In your command above, you have the redirection symbols reversed. The correct command is: nrsc5 91100000 1 >>hdlog.log 2>&1.

**Comment by BrodieBruce901** [comment]
That makes sense. I fixed the issue.
