### ISSUE TITLE
warning: ‘service_data_type_name’ defined but not used

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#148]
@argilo perhaps you might want to look at this. It seems your in the process of trying to clean up compiler warnings.

/usr/local/src/nrsc5/src/output.c:295:21: warning: ‘service_data_type_name’ defined but not used [-Wunused-function]
 static const char * service_data_type_name(unsigned int type)
                     ^~~~~~~~~~~~~~~~~~~~~~

**Comment by awesie** [comment]
That warning was introduced by #147 and is on my list of things to fix.
