### ISSUE TITLE
Stack smashing detected 

### ISSUE THREAD

**Issue by BrodieBruce901** [theori-io/nrsc5#16]
While decoding a stream I received this message on the latest ARM experimental branch code:

DEBUG frame.c:168: pdu_seq: 0, seq: 62, nop: 33
*** stack smashing detected ***: nrsc5 terminated
Aborted (core dumped)

**Comment by argilo** [comment]
@BrodieBruce901 I think this was fixed in #41. If not, feel free to re-open this issue.
