### ISSUE TITLE
Update readme to include Microsoft Visual C++ 2010 SP1 Redistributable Package

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#169]
The Microsoft Visual C++ 2010 SP1 Redistributable Package is required to run windows builds of NRSC5. @argilo feel like adding this to the readme? 

It's likely already installed for most users but it should be included in the case for those who don't and get a missing dll error.

It's located at https://www.microsoft.com/en-us/download/details.aspx?id=8328

**Comment by awesie** [comment]
My initial reaction is probably not add it to the README because we don't distribute any binary builds.

**Comment by pclov3r** [comment]
Maybe not. It seems like it's a niche issue anyways but thought i might bring it up since I had it on a brand new windows install.

**Comment by pclov3r** [comment]
I'll go ahead and close this. No longer needs to be open.
