### ISSUE TITLE
Failed to submit transfer 31! error

### ISSUE THREAD

**Issue by jeffgus** [theori-io/nrsc5#2]
I haven't had issues with other rtlsdr programs. rtl_fm, gqrx, and sdrtrunk all work. 
Does anyone have any ideas on how to get nrsc5 past this error?
I'm running on a Linux box (Fedora).

Exact sample rate is: 1488375.071248 Hz
Failed to submit transfer 31!
rtlsdr error: -5

**Comment by jeffgus** [comment]
I think I found the issue:
        -err = rtlsdr_read_async(dev, input_cb, &input, 0, RADIO_BUFFER);
        +err = rtlsdr_read_async(dev, input_cb, &input, 16, RADIO_BUFFER);

**Comment by awesie** [comment]
Thanks for reporting the problem. I'm happy to commit that change, but passing 0 should've used a default value (in rtl-sdr) of 15. Can you check whether the issue exists with a value of 15?

**Comment by jeffgus** [comment]
Oh! I'm fairly certain that I initially put 15, but then accidentally incremented the number in vim. I reduced it to 15 and re-built it and it works fine.
