### ISSUE TITLE
msys2-build script outdated

### ISSUE THREAD

**Issue by zefie** [theori-io/nrsc5#206]
with a fresh install of [msys2 (x64, msys2-x86_64-20190524.exe)](http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe), the script does not work because "MINGW_PACKAGE_PREFIX" is not defined

**Comment by ssl-3** [comment]
I also have exactly this issue.  Using the same version of msys2, fresh install.

**Comment by awesie** [comment]
Thanks for confirming. Since this is already documented in the README, I'm going to close this issue.
