### ISSUE TITLE
[Windows] File output very noisy

### ISSUE THREAD

**Issue by ferrellsl** [theori-io/nrsc5#207]
Directing output to a file results in very noisy audio file with lots of hiss and scratching.  The problem is present with both MSYS-32 and MSYS-64 builds.

**Comment by argilo** [comment]
Could you let me know the exact command line options you used to produce the audio file? Thanks in advance.

**Comment by ferrellsl** [comment]
Here's the command line:  nrsc5  -o test.wav 99.9 0

**Comment by argilo** [comment]
@ferrellsl #208 sholud fix the issue. I'd appreciate if you could test that on MSYS2.

**Comment by ferrellsl** [comment]
Works great now under MSYS2-64.   Thanks so much!

**Comment by argilo** [comment]
Glad to hear it. Thanks for letting us know about the problem.
