### ISSUE TITLE
{WINDOWS} Building NRSC5 Fails With Newest CMAKE and Make

### ISSUE THREAD

**Issue by simplio** [theori-io/nrsc5#209]
Building nrsc5 in MSYS2 mingw32 fails with this

make[2]: *** [src/CMakeFiles/nrsc5_object.dir/build.make:180: src/CMakeFiles/nrsc5_object.dir/conv_dec.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:278: src/CMakeFiles/nrsc5_object.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Windows 7 Home Premium 32bit

radio@radio-PC MINGW32 ~
$ cmake --version
cmake version 3.15.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

radio@radio-PC MINGW32 ~
$ make --version
GNU Make 4.2.1
Built for i686-pc-msys
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

I suggest updating your build to work with newer cmake and make.

**Comment by argilo** [comment]
Are you sure you followed the instructions correctly? I just updated my MSYS2 installation and was able to build nrsc5 in both 32-bit and 64-bit versions. I have cmake 3.15.6 and make 4.3, which are even newer than the versions you used.

Perhaps you should try removing the nrsc5 folder and rebuilding everything from scratch.
