### ISSUE TITLE
WAV output not working, IQ output working, and how to play from raw IQ data? [on Pinebook Pro OS]

### ISSUE THREAD

**Issue by QUANTA901** [theori-io/nrsc5#217]
sudo nrsc5 -o chk.wav 89.5 0 # creates 68 byte [header] file only
sudo nrsc5 -w chk.iq 89.5 0 # creates IQ data file, won't work without sudo?

**Comment by QUANTA901** [comment]
(nrsc5 89.5 0 won't play because of other issue)

**Comment by QUANTA901** [comment]
Uploading IQ data sample...

**Comment by QUANTA901** [comment]
play -t raw ... something?

**Comment by argilo** [comment]
I had a look at your I/Q file, and it appears this is not an HD Radio station. There are no digital sidebands present.

I'm closing this issue, because there does not appear to be any problem with nrsc5.
