### ISSUE TITLE
Audio died midstream. Station details and bit rate work but no sound

### ISSUE THREAD

**Issue by Prerunning** [theori-io/nrsc5#218]
Tried deleting everything and repeating the install but problem persist.
Sample audio plays correctly. I start it from msys2 and tune to 0 or 1 but same problem. Station details update but no sound
![aaaaaCapture](https://user-images.githubusercontent.com/49577532/78763348-e167e280-7939-11ea-83cc-5aed8a6e5b17.JPG)

**Comment by argilo** [comment]
Could you make an I/Q recording using the `-w` option and share the resulting file? Thanks.

**Comment by Prerunning** [comment]
> Could you make an I/Q recording using the `-w` option and share the resulting file? Thanks.

Sorry i would have replied sooner but i didnt see there was a reply. Shows 1 comment. But here is the -w you requested.
https://drive.google.com/open?id=1VTavmBlmmsEACXfkTUA08j3sMJt4D-xt

**Comment by Prerunning** [comment]
Bump

**Comment by argilo** [comment]
@Prerunning Please keep in mind that this project is maintained by volunteers in our spare time. We'll have a look at this soon, but I can't make any promises when exactly that will be.

**Comment by argilo** [comment]
The problem here lies with KJJJ-FM, not nrsc5. Using a USRP B200, I replayed your recorded signal and both of my hardware HD Radio receivers played silence once they locked onto the HD signal. So it would seem the station really is broadcasting silence.

**Comment by Prerunning** [comment]
Thank you for verifying that, I would have been troubleshooting forever.
