### ISSUE TITLE
Command flag to hide debug options and code line numbers / Make things a little less verbose?

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#226]
So, Curious if it would be worth to implement a flag to hide debug output and code line numbers. Pretty much to make things a bit less verbose. Instead of seeing `20:55:07 INFO  main.c:367: Station name: KWAV-FM` you'd see `20:55:07 Station name: KWAV-FM` with the flag as an example. 

I wasn't sure if this a good idea but i'd though it out anyways. Not sure how much work this would be as well. Might help to keep clutter down for newer users or something. 

Thoughts?

**Comment by awesie** [comment]
It is a minor change, so not difficult. I'm not a huge fan of adding it as a command flag. I would prefer it to be compile-time or, if we just decide that the information is not really useful any more, remove it.
