### ISSUE TITLE
"localhost" doesn't work using rtl_tcp with NRSC5

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#229]
So this is a bit strange. Trying to use "localhost" for the rtl_tcp host with NRSC5 doesn't work. It just fails with `19:35:46 Open remote device failed.`

However, Using 127.0.0.1 or localtest.me which resolves to 127.0.0.1 work perfectly fine. 

Fails on both Linux and Windows.

**Comment by awesie** [comment]
Hmm... it may be the case that rtl_tcp only listens on IPv4 by default and we are resolving localhost as IPv6.
