### ISSUE TITLE
Use with other SDRs

### ISSUE THREAD

**Issue by markjfine** [theori-io/nrsc5#259]
Has anyone (other than myself) looked at attempting to adapt this for other SDRs?

In particular, I started looking at developing an interface for an AirSpy HF+ Discovery (libairspyhf), which is gobs more sensitive and selective than an RTL-SDR.

On the surface it seems like it should be possible, but I haven't looked that deep into just how requisite some of the RTL-SDR API calls that are cited in nrsc5, but have no equivalent on the HF+. Might be a show-stopper.

**Comment by markjfine** [comment]
I should learn to scan first... apparently this has been addressed somewhat.

**Comment by argilo** [comment]
Closing as a duplicate of #122.
