### ISSUE TITLE
How to record IQ data for nrsc5 (Linux) right?

### ISSUE THREAD

**Issue by R8LBL** [theori-io/nrsc5#264]
Subj...
I tried IQ sample from sigidwiki, tried own recorded file from spyserver, but programme doesn't want to read them.
Which file extension, sample rate, bit depth should be for ability to play?
Thanks a lot!

**Comment by argilo** [comment]
nrsc5 expects complex unsigned 8-bit samples at a rate of 1488375 samples per second.
