### ISSUE TITLE
Potential issue running under Fedora 35

### ISSUE THREAD

**Issue by markjfine** [theori-io/nrsc5#265]
Seems to build fine, but just sits there with no response when run.
Most likely one of the updated FC35 libraries broke it. Digging to figure out which one...

**Comment by markjfine** [comment]
Disregard... multiple VM issues on a new installation.

**Comment by argilo** [comment]
Is this still an issue @markjfine? I just tested out nrsc5 in a Fedora 35 VM and it's working fine for me.

**Comment by markjfine** [comment]
Am running a F35 VM under Parallels, which had a really major problem with USB devices around that time (and still even might). I can try and rebuild/test, but I'm pretty sure that's what was going on if it works for you.

**Comment by argilo** [comment]
In VirtualBox I had to enable a virtual USB 3.0 controller to get sufficient USB performance.

You can test whether performance is sufficient with `rtl_test -s 1488375`.

**Comment by argilo** [comment]
I'll close this off for now, since there doesn't appear to be a problem in nrsc5 itself. Let me know if you find otherwise.

**Comment by markjfine** [comment]
Pretty sure I had that set in Parallels, but I'll test everything over the next couple of days and get back to you for sure.

**Comment by markjfine** [comment]
Brought up FC35 and tried nrsc5 as previously built and proceeded to get rtlsdr interface errors all over the place.

Rebuilt, remembering to cmake using the -DUSE_SSE option and it worked under the command line as well as through nrsc5-dui. 

The audio output was kind of choppy, but that's likely something completely unrelated to nrsc5 that I will need to iron out separately.

So just for closure: I think we're good on the FC35 front.

**Comment by argilo** [comment]
Thanks for confirming!

**Comment by markjfine** [comment]
Incidentally, regarding the choppy audio: Noticed in my Win11 VM (minGW cross-compiled on macOS) that the audio wouldn't drop out as rapidly as on my FC35 VM, but replayed the audio channel summaries each time a dropout occurred. Both VMs are set for USB 3.1 and the signals (once re-synchronised) were reported around the 11dB level on both sidebands, using a relatively local FM station.

I'm going to go out on a limb and suggest that the choppy audio on the Win11 VM, as well as on the FC35 VM, is related to an ongoing issue Parallels v17 has with USB connectivity/communications. I'm seeing way too many other similar kinds of  random USB-related issues with trackpad/mouse and external disk drives in Parallels and not natively under macOS that point to exactly that.

All FYI, just in case anyone else raises a similar audio issue.
