### ISSUE TITLE
Move from FAAD2 to fdk-aac to fix #260 broken Parametric Stereo implementation on subchannels?

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#278]
Was going over this https://github.com/theori-io/nrsc5/issues/260 and discovered that if I checkout this old build https://github.com/theori-io/nrsc5/tree/72c51de9c58f93200d011ade6e0954b27dcc83c4 and load a transcoded ADTS file into audacity it seems play correctly.

If I load that file into VLC it sounds awful and similar to the issues reported here.

Seems like https://github.com/theori-io/nrsc5/issues/88 may also be a similar issue to this. 

At that time it was proposed to move from FAAD2 to fdk-aac so I'm not sure if that will fix this issue.

I wonder if FAAD2 is not handling Parametric Stereo correctly. 

Just some obversions I noticed today.

@argilo not sure if any of this is useful 

EDIT: If you want convert stuff now a bit more easily you can checkout a old branch and use a separate converter https://github.com/theori-io/nrsc5/issues/88#issuecomment-336329564

**Comment by TheDaChicken** [comment]
I tried myself by checking out that old build and outputted adts. I played it through FFmpeg and it sounds good.

**Comment by pclov3r** [comment]
Was this with with a low bitrate channel that is is in mono with the current build?

**Comment by TheDaChicken** [comment]
Yes, it was a low bitrate at 30kbps. I forgot to mention that.

**Comment by pclov3r** [comment]
I'll close this in light of https://github.com/theori-io/nrsc5/pull/285
