### ISSUE TITLE
Add support for primary service mode MP2

### ISSUE THREAD

**Issue by argilo** [theori-io/nrsc5#305]
As noted in #301, WAMU is using primary service mode MP2, but nrsc5 cannot decode this mode yet.

I've added preliminary support in the [add-mp2 branch](https://github.com/theori-io/nrsc5/compare/add-mp2), and will open a pull request once I've had a chance to do some more testing.

It turns out that WAMU is using the P3 logical channel to send its station logos:

![1003_SLWAMU$010001Logo](https://github.com/theori-io/nrsc5/assets/583749/0d9cee33-b38e-439a-ac2b-9813e482d838)
![5002_SLWAMUHD020001Logo](https://github.com/theori-io/nrsc5/assets/583749/5a9e3d20-7c37-49d1-82e7-85c00d621b81)

My recording doesn't have any album art, but it's possible the P3 logical channel might also be used for that.

/cc @markjfine

**Comment by argilo** [comment]
Looking through my collection of recordings, I see that WAMU is not the only station sending out data on the P3 logical channel. WMUZ (Detroit) and WVEZ (Louisville) are also doing so. So these changes will also allow additional files to be decoded from stations using the MP3 mode.

**Comment by markjfine** [comment]
I pulled their logo off of their website in nrsc5-dui, which is the same here. Interesting that they'd devote an entire channel for station logos and optional album art.

HD1 is their main audio feed, a simulcast of American University's NPR-affiliated station. The second image is most likely for HD2 named 'Bluegrass Country' [Note: Those look like banjo frets, unless it's a ukulele, but definitely not a guitar 'cause only 4 strings]. Doubt HD1 would use any album art, but HD2 might. Worth playing around to find out for this, as well as other stations in the area that provided no logos via their main channels.

**Comment by markjfine** [comment]
Best I can tell WAMU is the only station in this region using P3 for this purpose at the moment. Nothing else looks out of the ordinary other than one station, WKYS, apparently using album art for ads. On another station, WIAD's HD2 (Channel Q) no longer has audio. The multipath being generated by a small plane flying around isn't helping with locking onto several marginal stations, but will continue to check these over time.

**Comment by argilo** [comment]
> Interesting that they'd devote an entire channel for station logos and optional album art.

In mode MP2, the P3 logical channel is only 12 kbps. That would be quite low for an audio channel, so offloading data to it seems like a reasonable idea.

> Worth playing around to find out for this, as well as other stations in the area that provided no logos via their main channels.

Using the P3 logical channel for data of any kind seems to be rare. Out of my collection of ~80 recordings, only three stations are doing so.

**Comment by argilo** [comment]
WMUZ doesn't have anything in their P3 data channel, it's just an endless stream of empty packets.

WVEZ is sending station logo & traffic data in P3.

**Comment by argilo** [comment]
The code is now ready for testing: #306.
