### ISSUE TITLE
[libnrsc5] Segment Fault

### ISSUE THREAD

**Issue by TheDaChicken** [theori-io/nrsc5#323]
I feel so weird creating a git issue after already being super active ANYWAY. 

I wrote a test c++ application to link against nrsc5

Simple as this:
```c++

extern "C"
{
#include <nrsc5.h>
};

int main() {
    nrsc5_t *radio = nullptr;
    nrsc5_open(&radio, 0);

    return 0;
}
```

Linking with:
```cmake
find_library(NRSC5_LIBRARIES nrsc5)
find_path(NRSC5_INCLUDE_LIB nrsc5.h)

add_executable(nrsc5_simple_test
        Main.cpp
        )
target_link_libraries(nrsc5_simple_test PRIVATE
        ${NRSC5_LIBRARIES})
target_link_directories(nrsc5_simple_test PRIVATE ${NRSC5_INCLUDE_LIB})
```

For some reason, I am getting a segment fault. GDB doesn't provide a location to the segment fault with "??" 
I feel like it's an issue with libusb? 
Am I linking incorrectly?
 
I used the same compiler (MYSYS2 MINGW-64) and built nrsc5 with support/win-cross-compile (though I used pacman -S libtool because that failed to grab properly). nrsc5 cl application works perfectly fine.

**Comment by markjfine** [comment]
USB interfacing in Windows with the stock usb library always seems to be a problem. I know of few Windows apps that don't require using Zadig to swap the dll out.

**Comment by pclov3r** [comment]
I wonder if https://github.com/theori-io/nrsc5/issues/317 would fix this?

**Comment by TheDaChicken** [comment]
Linking against the static nrsc5 by providing each library rtlsdr,faad2,libao,fftw,ws2_32 fixed it? 
Though is that a win????

**Comment by TheDaChicken** [comment]
related to libusb problem? not nrsc5
