### ISSUE TITLE
fftwf plans can be destroyed 

### ISSUE THREAD

**Issue by TheDaChicken** [theori-io/nrsc5#329]
`fftwf_cleanup` is called in input.c which causes any plans to be deleted. It is helpful when using Valgrind. But it kills created plans outside of the library when calling the API. [see here](https://github.com/FFTW/fftw3/issues/176#issuecomment-522286722) It results in segment faults.

**Comment by argilo** [comment]
Agreed that a library shouldn't be calling `fftwf_cleanup` (since its effects are global). I've opened #331 to remove it.

Looks like I was slightly too aggressive chasing down valgrind memory leak warnings in #143. :smile:
