### ISSUE TITLE
Updating MacPorts port for nrsc5

### ISSUE THREAD

**Issue by trodemaster** [theori-io/nrsc5#340]
Hi, I'm the maintainer for the unofficial macports port of nrsc5. One thing I would like to update is the build process downloading fftw instead of picking up the version already installed. Is there a search path I need to configure at build time? 

Issue I'm asked to resolve
https://trac.macports.org/ticket/67860

Source for the port
https://github.com/macports/macports-ports/tree/master/audio/nrsc5

Thanks for any guidance here!

**Comment by argilo** [comment]
I haven't looked at portfiles before, but it looks to me like fftw is not listed as a build dependency. Is that the problem?

**Comment by trodemaster** [comment]
I added fftw as a build dependency, but it's still not being found at build time. The logic I need to focus on is in the CMakeLists.txt file. macports has it's own structure under /opt that I need to have cmake look in.

**Comment by trodemaster** [comment]
Ah there was another "sub port" that was needed to provide fftw 3 single precision library. https://github.com/macports/macports-ports/pull/23301/files

FYI here is the port page
https://ports.macports.org/port/nrsc5/details/

Closing this as all that remains is to work the process to get my PR merged. Thanks for nrsc5 I listen to a lot of HD radio using this program.

**Comment by argilo** [comment]
I'm glad you were able to solve it.

I suspect you can remove the `faad2` dependencies, since nrsc5 must build its own patched version of faad2 which adds HDC support.
