### ISSUE TITLE
SIS messages?

### ISSUE THREAD

**Issue by itdaniher** [theori-io/nrsc5#38]
I'm interested in trying to use the SIS Parameter Message and possibly station location from the SIS PDU Messages to establish a crude time / location for a distributed sensing project, but it looks like this information isn't decoded right now. It looks like I'd need to start with `frame.c` - maybe in `frame_process` but I'd appreciate any pointers in the interim.

Cheers!

**Comment by argilo** [comment]
@itdaniher SIS message type 4 would need to be implemented here:

https://github.com/theori-io/nrsc5/blob/12d9526f89838b38b14b4d25793c0ceb06e9b68d/src/pids.c#L122-L124

Note that SIS parsing is only on the experimental branch currently; it hasn't been merged to master yet.

The format is described in http://www.nrscstandards.org/SG/NRSC-5-C/1020sI.pdf section 4.4.

**Comment by itdaniher** [comment]
Brilliant, thanks! I'm actually starting with processing time transmissions (MSG ID 0b0111 / first few indexes) / SIS Parameter Messages first, but it looks like doing so will require introducing state in the PIDS parsing to accumulate time metadata. I haven't looked enough at the code yet to figure out how to most elegantly do so - maybe define relevant structs in pids.h?

Cheers!

**Comment by argilo** [comment]
Yep, storing state in a structs would make sense. There are other places that's done already.

**Comment by argilo** [comment]
#79 implements most of the remaining pieces, apart from Universal Short Station Name.

**Comment by argilo** [comment]
I'm going to close this off now, since nearly all SIS messages are now decoded.
