### ISSUE TITLE
Basic samp_rate & data encoding format for use w/GNU Radio

### ISSUE THREAD

**Issue by Teque5** [theori-io/nrsc5#47]
I've tried piping my own data into nrsc5 and I've also tried reading in your sample file. I could futz with it for another hour, but it would be useful if you told us what the sample rate and encoding was of the sample file in the /support directory.

My current <incorrect> guess (since I can't demod it normally):
samp_rate = 1488375
encoding = interleaved signed short (16 bit I, 16 bit Q)

When I use your tool the file is around 9 seconds long, which at 1448KHz sample rate would be about 4 bytes per sample.

What do I have wrong? Is there a header in the sample file?

**Comment by awesie** [comment]
It is designed for rtl-sdr, so the input is what I get from librtlsdr. I believe it is interleaved unsigned byte. The sample rate should be 1488375.

See https://www.reddit.com/r/RTLSDR/comments/2qrfvn/help_with_iq_samples/cn8w01e/.

**Comment by argilo** [comment]
The sample rate is 1488375 and the format is interleaved unsigned bytes. The same format that rtl_sdr uses.

**Comment by Teque5** [comment]
Ok. So the file type is complex interleaved 8 bit. The following GNU Radio flowgraph may help someone else. The screenshot also shows how to convert USRP complex float into this format.
![screenshot from 2017-08-08 14-14-27](https://user-images.githubusercontent.com/784749/29094909-f19b4e58-7c43-11e7-8dcb-417f7a38589d.png)

**Comment by argilo** [comment]
@Teque5 That doesn't look right. You would need to add / subtract 127 when converting signed to/from unsigned bytes.

**Comment by Teque5** [comment]
@argilo The interleaved short to complex block (and vice-versa) has this built-in within GNU Radio.

**Comment by argilo** [comment]
Yep, that looks like the right way.
