### ISSUE TITLE
Benchmarking speed of tuner auto gain control for RTL_FM v NRSC

### ISSUE THREAD

**Issue by classicjazz** [theori-io/nrsc5#52]
Just wondering why the AGC tuning takes so much longer in NRSC v RTL_FM.

Tuning FM 90.1 with this RTL_FM consistently takes less than a second including the auto gain control, using a 2017 iMac.
`
rtl_fm -M wbfm -f 90.1M | play -r 32k -t raw -e s -b 16 -c 1 -V1 -
`
Tuning the same station with NRSC, the AGC testing alone (just separate from decoding digital feed) takes between 4-8 seconds. Total time from start to synchronization takes between 8-12 seconds.

Not sure if this is a true apples to apples comparison of the two AGCs. But thought it was valuable to document. Oddly, if I restart NRSC over and over again every 30 seconds, I get a different "best gain" result. Sometimes, 120 best gain, other times 200. Tested dB before determining best gain also varies considerably in hammer testing. Sometimes low 20s. other times 40+ dB.

`Found Rafael Micro R820T tuner
Exact sample rate is: 1488375.071248 Hz
14:48:37 INFO  main.c:63: Gain: 0.0 dB, CNR: 5.792418 dB
14:48:37 INFO  main.c:63: Gain: 0.9 dB, CNR: 8.088401 dB
14:48:37 INFO  main.c:63: Gain: 1.4 dB, CNR: 8.523772 dB
14:48:38 INFO  main.c:63: Gain: 2.7 dB, CNR: 9.771772 dB
14:48:38 INFO  main.c:63: Gain: 3.7 dB, CNR: 10.299677 dB
14:48:38 INFO  main.c:63: Gain: 7.7 dB, CNR: 10.275181 dB
14:48:38 INFO  main.c:63: Gain: 8.7 dB, CNR: 10.556330 dB
14:48:38 INFO  main.c:63: Gain: 12.5 dB, CNR: 10.545234 dB
14:48:38 INFO  main.c:63: Gain: 14.4 dB, CNR: 10.643739 dB
14:48:39 INFO  main.c:63: Gain: 15.7 dB, CNR: 10.469473 dB
14:48:39 INFO  main.c:63: Gain: 16.6 dB, CNR: 8.750142 dB
14:48:39 INFO  main.c:63: Gain: 19.7 dB, CNR: 9.875199 dB
14:48:39 INFO  main.c:63: Gain: 20.7 dB, CNR: 10.480328 dB
14:48:39 INFO  main.c:63: Gain: 22.9 dB, CNR: 9.716369 dB
14:48:39 INFO  main.c:63: Gain: 25.4 dB, CNR: 10.508485 dB
14:48:40 INFO  main.c:63: Gain: 28.0 dB, CNR: 8.977230 dB
14:48:40 INFO  main.c:63: Gain: 29.7 dB, CNR: 9.847438 dB
14:48:40 INFO  main.c:63: Gain: 32.8 dB, CNR: 8.676806 dB
14:48:40 INFO  main.c:63: Gain: 33.8 dB, CNR: 7.808435 dB
14:48:40 INFO  main.c:63: Gain: 36.4 dB, CNR: 8.110155 dB
14:48:40 INFO  main.c:63: Gain: 37.2 dB, CNR: 7.723773 dB
14:48:41 INFO  main.c:63: Gain: 38.6 dB, CNR: 7.766683 dB
14:48:41 INFO  main.c:63: Gain: 40.2 dB, CNR: 7.373116 dB
14:48:41 DEBUG main.c:67: Best gain: 144
14:48:44 DEBUG sync.c:267: First block @ 15
14:48:45 DEBUG sync.c:267: First block @ 0
14:48:45 INFO  sync.c:245: Synchronized!
14:48:45 DEBUG pids.c:114: Station Name: WRTI-FM
14:48:45 DEBUG pids.c:103: Country: US, FCC facility ID: 65190`

Here's another example, using WHYY

`14:52:44 INFO  main.c:183: [0] Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Exact sample rate is: 1488375.071248 Hz
14:52:44 INFO  main.c:63: Gain: 0.0 dB, CNR: 8.627121 dB
14:52:45 INFO  main.c:63: Gain: 0.9 dB, CNR: 10.663241 dB
14:52:45 INFO  main.c:63: Gain: 1.4 dB, CNR: 10.967073 dB
14:52:45 INFO  main.c:63: Gain: 2.7 dB, CNR: 12.141378 dB
14:52:45 INFO  main.c:63: Gain: 3.7 dB, CNR: 12.428569 dB
14:52:45 INFO  main.c:63: Gain: 7.7 dB, CNR: 12.798332 dB
14:52:45 INFO  main.c:63: Gain: 8.7 dB, CNR: 12.459588 dB
14:52:46 INFO  main.c:63: Gain: 12.5 dB, CNR: 12.804129 dB
14:52:46 INFO  main.c:63: Gain: 14.4 dB, CNR: 11.821280 dB
14:52:46 INFO  main.c:63: Gain: 15.7 dB, CNR: 12.096880 dB
14:52:46 INFO  main.c:63: Gain: 16.6 dB, CNR: 11.716665 dB
14:52:46 INFO  main.c:63: Gain: 19.7 dB, CNR: 10.693796 dB
14:52:46 INFO  main.c:63: Gain: 20.7 dB, CNR: 11.575437 dB
14:52:47 INFO  main.c:63: Gain: 22.9 dB, CNR: 11.434118 dB
14:52:47 INFO  main.c:63: Gain: 25.4 dB, CNR: 10.581103 dB
14:52:47 INFO  main.c:63: Gain: 28.0 dB, CNR: 10.282454 dB
14:52:47 INFO  main.c:63: Gain: 29.7 dB, CNR: 10.110866 dB
14:52:47 INFO  main.c:63: Gain: 32.8 dB, CNR: 9.353167 dB
14:52:47 DEBUG main.c:67: Best gain: 125
14:52:50 DEBUG sync.c:267: First block @ 27
14:52:51 INFO  sync.c:245: Synchronized!
`

**Comment by argilo** [comment]
Addressed in #65.
