### ISSUE TITLE
Include path not properly set in CMake build definitions

### ISSUE THREAD

**Issue by docprofsky** [theori-io/nrsc5#67]
The include path is not properly set in the CMake build definitions. This causes problems when headers are not in the compiler default location. When building, this results in the compiler being unable to find `fftw3.h`. This can be fixed by passing the include directory(ies) for the libraries to `include_directories` in CMake.

This is probably not a problem for the developers if their compiler include path covers the headers for all of the dependencies. I use MacOS with MacPorts, which places headers in `/opt/local/include`, outside of the compiler include path.

I have fixed this with these changes, however this assumes that `fftw3.h` is in the same location as the rest of the headers.
https://gist.github.com/docprofsky/3ab3e1e4e29ea534548595d9437fa3c7

**Comment by awesie** [comment]
Using FindPkgConfig and pkg_check_modules is probably the right way to fix the ffw3f and rtlsdr dependencies.
