### ISSUE TITLE
rtl_tcp support

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#86]
So I thought it might be useful to have rtl_tcp support built in.

**Comment by argilo** [comment]
By the way, you can do this today by running:
```
rtl_tcp -a 0.0.0.0 -f 100.3M -s 1488375 -g 20
```
```
nc 192.168.1.111 1234 | src/nrsc5 -r - 0
```
Building support into nrsc5 would save you from having to specify the frequency, sample rate and gain on the server, and from having to use `nc` on the client.

**Comment by pclov3r** [comment]
@argilo Interesting. Looks useful for now.

People that have a rtl-sdr in some remote location may benefit form having this built in.

**Comment by pclov3r** [comment]
@argilo your suggestion works for me and it even works on Windows as well.

**Comment by adrianboyko** [comment]
Voting for this enhancement. I use multiple clients that share an rtl_tcp running on a Raspberry Pi. Needing to rerun rtl_tcp on the Pi, every time I want to listen to nrsc5 on my PC, is inconvenient.

**Comment by fanlessfan** [comment]
Voting for this enhancement.

**Comment by awesie** [comment]
Is the specific request to have nrsc5 connect to a rtl_tcp server, modify the server's current frequency and gain, and decode the audio?

**Comment by fanlessfan** [comment]
That’s more convenient than login to the server to run the rtf-tcp.
