### ISSUE TITLE
Update README to show example of usage without piping to external player

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#93]
In light of https://github.com/theori-io/nrsc5/issues/92 I discovered that the README under example usage doesn't include an example of how to use it without piping the audio to a external player. 

Probably would be helpful for new users if there was a example such as `nrsc5 90.5 0` to indicate that it doesn't need to be piped to a external player.

**Comment by argilo** [comment]
Fixed in #94.
